### ISSUE TITLE
paths rotate_shear.py

### ISSUE THREAD

**Issue by hywu** [vargatn/xpipe#5]
1. `python rotate_shear.py --wconfig` crashes with error:
main_xconfig_fname = paths.fullpaths["xconfig"] 
KeyError: 'xconfig'

2. `python rotate_shear.py` crashes at:
 with open(paths.fullpaths['flist']) as file: 
    flist = file.read().splitlines()

**Comment by vargatn** [comment]
Updated rotate_shear.py and shapecov.py to the current pipeline version, tested on Lensing without borders data (see committed example file in settings).
